# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

posterior_h_cpp <- function(h_n, v_n, W, alpha, beta) {
    .Call('_rMMLE_posterior_h_cpp', PACKAGE = 'rMMLE', h_n, v_n, W, alpha, beta)
}

posterior_eta_cpp <- function(eta_n, v_n, W, alpha, beta) {
    .Call('_rMMLE_posterior_eta_cpp', PACKAGE = 'rMMLE', eta_n, v_n, W, alpha, beta)
}

grad_posterior_eta_cpp_R <- function(eta_n, v_n, W, norms_W, alpha, beta) {
    .Call('_rMMLE_grad_posterior_eta_cpp_R', PACKAGE = 'rMMLE', eta_n, v_n, W, norms_W, alpha, beta)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call('_rMMLE_mvrnormArma', PACKAGE = 'rMMLE', n, mu, sigma)
}

likelihood_V_W_cpp <- function(V, W, alpha, beta) {
    .Call('_rMMLE_likelihood_V_W_cpp', PACKAGE = 'rMMLE', V, W, alpha, beta)
}

sample_gibbs_cpp <- function(v_n, W, h_n, alpha = 1, beta = 1, iter = 100L, burnin = 0.5) {
    .Call('_rMMLE_sample_gibbs_cpp', PACKAGE = 'rMMLE', v_n, W, h_n, alpha, beta, iter, burnin)
}

sample_gibbs_cpp_N <- function(V, W, H_init, alpha = 1, beta = 1, iter = 100L, burnin = 0.5) {
    .Call('_rMMLE_sample_gibbs_cpp_N', PACKAGE = 'rMMLE', V, W, H_init, alpha, beta, iter, burnin)
}

sample_gibbs_z_cpp <- function(v_n, W, C, alpha = 1, beta = 1, iter = 100L, burnin = 0.5) {
    .Call('_rMMLE_sample_gibbs_z_cpp', PACKAGE = 'rMMLE', v_n, W, C, alpha, beta, iter, burnin)
}

sample_hmc_cpp <- function(v_n, W, h_n_current, alpha = 1, beta = 1, L = 10L, epsilon = 0.01, iter = 100L) {
    .Call('_rMMLE_sample_hmc_cpp', PACKAGE = 'rMMLE', v_n, W, h_n_current, alpha, beta, L, epsilon, iter)
}

sample_mala_cpp <- function(v_n, W, h_n_current, alpha = 1, beta = 1, delta = 0.01, iter = 100L) {
    .Call('_rMMLE_sample_mala_cpp', PACKAGE = 'rMMLE', v_n, W, h_n_current, alpha, beta, delta, iter)
}

sample_metropolis_h_reparam_cpp <- function(v_n, W, h_n_current, alpha = 1, beta = 1, step = 1, iter = 100L) {
    .Call('_rMMLE_sample_metropolis_h_reparam_cpp', PACKAGE = 'rMMLE', v_n, W, h_n_current, alpha, beta, step, iter)
}

posterior_h_cpp_ <- function(h_n, v_n, W, alpha, beta) {
    .Call('_rMMLE_posterior_h_cpp_', PACKAGE = 'rMMLE', h_n, v_n, W, alpha, beta)
}

sample_nuts_cpp <- function(v_n, W, h_n_current, alpha = 1, beta = 1, epsilon = 0.01, iter = 100L) {
    .Call('_rMMLE_sample_nuts_cpp', PACKAGE = 'rMMLE', v_n, W, h_n_current, alpha, beta, epsilon, iter)
}

variational_ch_cpp <- function(v_n, W, alpha_var, beta_var, alpha = 1, beta = 1, maxiters = 100L) {
    .Call('_rMMLE_variational_ch_cpp', PACKAGE = 'rMMLE', v_n, W, alpha_var, beta_var, alpha, beta, maxiters)
}

